### ISSUE TITLE
[🐞] 1.4.1 breaks node/express deployment due to wrong import paths of Qwik-city modules in entry.*.mjs 

### ISSUE THREAD

**Issue by genox** [BuilderIO/qwik#5774]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I am using node/express for deployment.

in 1.4.0, a build generates an entry.express.mjs that imports these modules from the same directory as the entry file is located:

```
entry.express.mjs@1.4.0:

import { getNotFound } from "./@qwik-city-not-found-paths.js";
import { isStaticPath } from "./@qwik-city-static-paths.js"; 
```

In 1.4.1, the import path's are now absolute, referring to a location that only exists during the docker file build stage:

```
entry.express.mjs@1.4.1:

import { getNotFound } from "/build/packages/qwik/server/@qwik-city-not-found-paths.js";
import { isStaticPath } from "/build/packages/qwik/server/@qwik-city-static-paths.js"; 
```

This causes the project to not being able to be started with `node ./server/entry.express.mjs` which is how it was successfully working in 1.4.0 because the directory does not exist.

Obviously this doesn't affect local build/run since absolute paths on the same filesystem are working just fine, but with an intermediary build stage, it fails.

It also seems to affect other deployment methods. (see discord)

The error message in production:

```
2024-01-26T14:13:08.978360686Z  2024-01-26T14:13:08.978362670Z Node.js v20.11.0 2024-01-26T14:13:14.676704118Z node:internal/modules/esm/resolve:264 2024-01-26T14:13:14.676762088Z throw new ERR_MODULE_NOT_FOUND( 2024-01-26T14:13:14.676768090Z ^ 2024-01-26T14:13:14.676771397Z  2024-01-26T14:13:14.676775164Z Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/build/packages/qwik/server/@qwik-city-not-found-paths.js' imported from /app/server/entry.express.mjs 2024-01-26T14:13:14.676778580Z at finalizeResolution (node:internal/modules/esm/resolve:264:11) 2024-01-26T14:13:14.676781896Z at moduleResolve (node:internal/modules/esm/resolve:917:10) 2024-01-26T14:13:14.676785333Z at defaultResolve (node:internal/modules/esm/resolve:1130:11) 2024-01-26T14:13:14.676789031Z at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12) 2024-01-26T14:13:14.676792798Z at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25) 2024-01-26T14:13:14.676796255Z at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38) 2024-01-26T14:13:14.676801865Z at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39) 2024-01-26T14:13:14.676810182Z at link (node:internal/modules/esm/module_job:84:36) { 2024-01-26T14:13:14.676813938Z code: 'ERR_MODULE_NOT_FOUND', 2024-01-26T14:13:14.676817545Z url: 'file:///build/packages/qwik/server/@qwik-city-not-found-paths.js' 2024-01-26T14:13:14.676821172Z } 2024-01-26T14:13:14.676824658Z  2024-01-26T14:13:14.676828065Z Node.js v20.11.0 
```

I cannot provide a reproduction as it is a runtime error in a docker image after build.

### Reproduction

none

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 13.64 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 4.0.2 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  Browsers:
    Brave Browser: 121.1.62.153
    Chrome: 121.0.6167.85
    Safari: 17.2.1
```

**Comment by genox** [comment]
Might be related to this change:

https://github.com/BuilderIO/qwik/commit/d2380feb80a221c0376d1754838cc24376baab06

**Comment by tuurbo** [comment]
Same or similar issue with Fastify adapter and Qwik 1.4.1
```
node:internal/modules/esm/load:236
    throw new ERR_UNSUPPORTED_ESM_URL_SCHEME(parsed, schemes);
          ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:236:11)
    at defaultLoad (node:internal/modules/esm/load:128:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:409:13)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:56)
    at new ModuleJob (node:internal/modules/esm/module_job:65:26)
    at #createModuleJob (node:internal/modules/esm/loader:303:17)
    at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:260:34)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:241:17)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:21) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```
```
 System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 14.84 GB / 31.68 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.11.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.144)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @builder.io/partytown: ^0.9.0 => 0.9.0
    @builder.io/qwik: 1.4.2 => 1.4.2
    @builder.io/qwik-city: 1.4.2 => 1.4.2
    vite: 5.0.12 => 5.0.12
```

**Comment by wmertens** [comment]
Ok I'll revert that change. I was trying to fix preview not working because the import path is wrong for preview.
